theme: jekyll-theme-cayman
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: EECS 4313 - C.A.S.A.Y Group Website
description: [A website to contain our assignments for EECS4313]
